### ISSUE TITLE
archive_file produces different results on different OSs

### ISSUE THREAD

**Issue by maxrothman** [hashicorp/terraform-provider-archive#34] opened 2018-12-19 22:38 UTC
### Affected Resource(s)
- datasource `archive_file`
- resource `aws_lambda_function`

### Terraform Configuration Files
```hcl
data "archive_file" "zip" {
    type        = "zip"
    source_file = "${var.source_code_path}"
    output_path = "zip/${basename(var.source_code_path)}.zip"
}

resource "aws_lambda_function" "fn" {
    filename = "${data.archive_file.zip.output_path}"
    source_code_hash = "${data.archive_file.zip.output_base64sha256}"
    function_name = "${var.function_name}"
    role = "${aws_iam_role.role.arn}"
    handler = "${var.handler_name == "" ? "${replace("${basename(var.source_code_path)}",".py","")}.lambda_handler" : var.handler_name}"
    runtime = "python3.6"
    timeout = "${var.timeout}"

    environment {
        variables = "${var.env_vars}"
    }
}
```
After applying on Windows, planning on Mac indicates that `source_code_hash` has changed, even though the content of the code has not changed. This is because `archive_file` produces equivalent but not identical results on Mac and Windows.

### Expected Behavior
The lambda updates IFF the source code changes

### Actual Behavior
The lambda updates when the source code changes OR if you run terraform on a different OS

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` on Windows
2. `terraform plan` on Mac
3. observe that it thinks it needs to update the lambda

**Comment by takayamaki** [comment] 2019-02-07 09:47
I had encountered this issue too.
We used Lubuntu 16.04 and macOS 10.13.6.

**Comment by bboe** [comment] 2019-03-01 17:13
I noticed that the produced zip file differs depending on the permissions of the source file. Why would the source file permissions be different? One common case is having a different umask between systems. For example, my laptop's default umask is `0022` thus when I clone a repository, the permissions of non-executable files are `-rw-r--r--`. However, the [Amazon Linux 2 AMI](https://aws.amazon.com/amazon-linux-2/) has a default umask of `0002` thus newly created (or cloned) files have permissions of `-rw-rw-r--`.

Prior to realizing that archive_file worked for directories, I wrote a little [tool to produce deterministic zip files](https://github.com/bboe/deterministic_zip/blob/6cda2f75741a8c24ccbee6defaff78dd0ca2a27a/deterministic_zip/__init__.py#L21). To handle permissions it either sets all files in the zip to be `-r--r--r--` or `-r-xr-xr-x` depending on if the file should be executable or not. I could see a use case for also handling the write permission, but I have yet to need that.

The reason for these permissions is, as [according to the lambda documentation](https://docs.aws.amazon.com/lambda/latest/dg/deployment-package-v2.html) all files should have global read permissions. While it's not explicitly stated, I interpret that to mean any executables thus need to have global execute permissions. Hence why I think zip files created by this tool should apply consistent permissions to all users (i.e., user, group, other sections).

**Comment by quixand** [comment] 2019-05-29 13:49
I came across this issue where my centos 7 VM has different permissions for mounted volumes and was removing the execute bit. Annoyingly, trying to change the permissions doesn't work (see https://superuser.com/questions/1083393/virtualbox-guest-shared-folder-ignoring-umask) 

some kind of parameter on the archive_file data source block to set the execute bit would make sense as its generating the zip, but wouldn't work for my scenario.

**Comment by saveriomiroddi** [comment] 2019-05-29 14:03
For reference, we experienced the same problem; there are multiple causes for a zip archive with the same data to be binary different; not only the permissions, but also compression method and modification time may vary.

We've internally solved the problem by adding an option to the archive provider: https://github.com/saveriomiroddi/terraform-provider-archive-dev/tree/sav-normalize_files_metadata_option

We plan to open a PR, hoping that this solution will be accepted.

**Comment by quixand** [comment] 2019-06-06 11:21
perhaps a better solution would be to provide a source hash i.e.
```source_code_hash = "${data.archive_file.zip.input_base64sha256}"```

After all, the source_code_hash element is used to trigger an update on change so inspecting the source rather than the exported binary zip should fulfill the same requirement.

**Comment by saveriomiroddi** [comment] 2019-06-06 15:56
> perhaps a better solution would be to provide a source hash i.e.
> `source_code_hash = "${data.archive_file.zip.input_base64sha256}"`
> 
> After all, the source_code_hash element is used to trigger an update on change so inspecting the source rather than the exported binary zip should fulfill the same requirement.

That would be ideal, but I don't think it would work - assuming that AWS returns the archive hash, it would make Terraform think the local and remote versions are different, causing it to be uploaded every time.

**Comment by quixand** [comment] 2019-06-06 16:24
I think you misunderstand. AWS does indeed confirm the hash of the uploaded binary(https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html) but I expect this is intended to confirm that the binary has uploaded correctly. However, according to the terraform docs the source_code_hash element in aws_lambda_function is "Used to trigger updates". so it would be good to have a trigger that can identify that the code has changed separate from the hash result of the binary.

Of course this doesn't answer the question, why is the binary output different across OS's. And if terraform is verifying the hash of the binary in the background anyway this still needs to be resolved.

**Comment by maxrothman** [comment] 2019-06-06 22:11
That only works when you're only archiving a single file. What if you're archiving a directory?

**Comment by bboe** [comment] 2019-06-06 23:15
I submitted this PR some time ago but haven't heard anything from maintainers of the project. 🤷‍♂ 

https://github.com/terraform-providers/terraform-provider-archive

**Comment by saveriomiroddi** [comment] 2019-06-07 06:25
> That only works when you're only archiving a single file. What if you're archiving a directory?

This can be achieved in different and more/less thorough ways. In the simplest implementation, one would just concatenate the files content. However, an exact algorithm needs also to take into account a few other factors in order not to raise false negatives, eg. the directory structure.

**Comment by Sodki** [comment] 2019-06-11 15:44
This is *not* a straight forward task and I seriously doubt that Terraform is going to fix it. A couple of years ago a new project called TorrentZip was created by the MAME community to tackle this exact problem (reproducible zip files across multiple operating systems). More information here: http://rescene.wikidot.com/torrentzip

It seems that someone implemented a Go version of it: https://github.com/uwedeportivo/torrentzip

**Comment by saveriomiroddi** [comment] 2019-06-11 16:32
> This is **not** an easy or straight forward task (even if it looks like it) and I seriously doubt that Terraform is going to fix it. A couple of years ago a new project called TorrentZip was created by the MAME community to tackle this exact problem (reproducible zip files across multiple operating systems). More information here: http://rescene.wikidot.com/torrentzip
> 
> It seems that someone implemented a Go version of it: https://github.com/uwedeportivo/torrentzip

We actually use the fork mentioned above at our company, and it works as expected, although we don't have many platforms - only a few recent Ubuntu and Mac systems.

There are some simplifications that make it easier. In the fork, for example, compression is disabled (Store algorithm is used), which I think is a big issue for projects that needs it, but not for Lambda packages.

**Comment by saveriomiroddi** [comment] 2019-07-05 14:15
I've created a PR with a new functionality for solving this problem (see #47).

We've been using it in my team for months by now and it solves the problem as expected.

We don't have a large body of archives, but still there are a handful of lambda function resources using a mixture of single files and directories; the O/Ss involved are Mac and Ubuntu.

**Comment by virgofx** [comment] 2020-03-21 20:01
@appilon @radeksimko Any chance we could get this merged into the module? This issue has been around for awhile and has the most upvotes/comments

**Comment by sapher** [comment] 2020-03-26 13:25
Still having the issue today

**Comment by xarses** [comment] 2020-03-31 20:56
I can confirm this behavior still exists as the patch from @saveriomiroddi wasn't merged (sadly). With out these changes the archive_file production isn't idempotent. At a minimum this should be reflected in the documentation so that appropriate steps can be taken to avoid the problem

**Comment by appilon** [comment] 2020-05-12 19:26
Hello all, apologies for the long time without any word, we will try to be better about that going forward. Unfortunately solving this problem is inherently difficult, we recently setup multi-os testing in #71 to try and have a better chance at catching problems such as this, but this issue specifically isn't something that we can practically catch in CI.

We are evaluating the solutions proposed in #41 and #47, but in this circumstance trying to code against operating system or library defaults just so a common pattern for a different provider is resolved, might not be something we want to set precedent for in an individual provider (our apologies if that is a frustrating stance to take).

With that said, we are still looking at the two proposed PRs, and will be attempting to either come up with a solution, or provide a final word/guidance. We understand a large amount of the frustration comes with the lack of communication, for that we apologize and will do better.

**Comment by virgofx** [comment] 2020-05-13 00:17
@appilon Thanks so much for the update. Looking forward to a hopeful resolution soon.

**Comment by saveriomiroddi** [comment] 2020-05-15 11:33
> Hello all, apologies for the long time without any word. Unfortunately solving this problem is inherently difficult

@appilon I don't understand this sentence. It implies that there is currently no known solution.

The logic provided is #47 doesn't meet the design expectations, which is fair point (and makes the closing appropriate), but it does provide a solution. Forcing the file mode is not a complete solution, as it solves the problem only for a subset of users.

Could you formulate a specification that can be discussed? The changes themselves could be straightforward (this doesn't imply "easy"), so with a specification, there is a starting point.

Right now, I think the sub-problems are:

1. make the file mode consistent; this can be achieved by allowing the user to select it
2. make the compression mode consistent; should this be user-selectable?
3. make the modification data consistent; how can this be solved in the user resource interface?

if those are defined, I could have a look of them individually.

**Comment by timwsuqld** [comment] 2020-07-16 00:34
While this is a 2 year old comment (https://github.com/hashicorp/terraform/issues/18422#issuecomment-403908165), it suggests that zip files should be created by a build process. 
https://www.reddit.com/r/Terraform/comments/aupudn/building_deterministic_zips_to_minimize_lambda/ also handles it by creating zip files in the build process instead of using `archive_file`

It would be great if Hashicorp would give an official status on if `archive_file` is the "wrong" way to be doing this. There are a bunch of different ways to produce deterministic zip files in your build process, including `strip-nondeterminism` from Debian (https://salsa.debian.org/reproducible-builds/strip-nondeterminism) and deterministic_zip https://github.com/bboe/deterministic_zip

**Comment by virgofx** [comment] 2020-07-17 02:51
Yeah, I'd love to see some traction on this issue. I don't think this is out of scope of Terraform though. As this thread has mentioned, there are tons of workarounds to get it working. Just need Hashicorp to actually put some resources on this and get it working.

**Comment by saveriomiroddi** [comment] 2021-03-21 08:59
Hi there! I've deleted all of my comments are closed the PR; please don't (manually) CC me.

**Comment by kmoe** [comment] 2021-04-13 14:51
There is a proposed workaround for this issue in #90, which adds an optional `output_file_mode` attribute to force consistency in file modes across OSs.

I would be very grateful if some of you experiencing this could test this fix by building @virgofx's provider and running it locally. You can find instructions for using a locally built provider here: https://www.terraform.io/docs/cli/config/config-file.html#development-overrides-for-provider-developers

**Comment by kmoe** [comment] 2021-05-05 08:06
The workaround in https://github.com/hashicorp/terraform-provider-archive/pull/90 has been merged. If `output_file_mode` does not solve your problem, please comment on this issue or open a new one.

**Closed by kmoe** 2021-05-05 08:06 UTC

**Comment by cristianburca** [comment] 2022-09-07 15:21
worked for me as well. Thanks @davidalger

**Comment by digitalkaoz** [comment] 2023-11-07 14:26
@davidalger cam across this one. we are uploading our compiled go code into the zip, but the hashes are unstable (like the whole internet has this problem). sadly `file(binary_file)` wont work. how you deal with that?
