### ISSUE TITLE
Using multiple source files for Lambda with archive_file

### ISSUE THREAD

**Issue by sanspace** [hashicorp/terraform-provider-archive#56] opened 2019-11-18 20:56 UTC
### Terraform Version

```
Terraform v0.12.15
+ provider.archive v1.3.0
+ provider.aws v2.37.0
```

### Affected Resource(s)

archive_file

### Terraform Configuration Files
```hcl
data "archive_file" "lambda" {
  type        = "zip"
  source_dir  = "../src/"
  output_path = "../dist/lambda_src.zip"
}
```

### Expected Behavior

archive should contain only the files.

### Actual Behavior

archive has a directory that contains the files

### Steps to Reproduce

Use the [example](https://github.com/terraform-providers/terraform-provider-aws/blob/master/examples/lambda/main.tf#L8-L12) with more than one source file.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- Using multiple source files for Lambda with archive_file

TF example with just one file: https://github.com/terraform-providers/terraform-provider-aws/blob/master/examples/lambda/main.tf#L8-L12 In my case, it's more than one source file.

**Comment by gurre** [comment] 2020-03-04 19:34
Have you checked using the CLI? If on macOS it adds the folder.

`unzip -vl lambda_function_payload.zip`

**Comment by AzySir** [comment] 2021-08-17 12:12
Have we put any consideration into this. I have this same issue with Lambda creations. There are packages being zipped but I also need to add my handler.py into the same zip - but can't seem to do so with this provider. 

I thought this might be a common use-case does anyone have a work around?

**Comment by jcollum** [comment] 2021-09-07 23:07
Seems like a reasonable use case, I have a handler in `dist` (compiled from ts) and some packages in `node_modules`. Doesn't seem crazy to want to package them up into the same zip.

**Comment by simonweil** [comment] 2022-07-05 08:17
Any chance to get this implemented?

**Comment by bendbennett** [comment] 2022-11-16 16:07
@sanspace can I confirm that this is still an issue with the latest version of the provider?

When using `v2.2.0` with the following configuration:

```terraform
data "archive_file" "lambda" {
  type        = "zip"
  source_dir  = "src/"
  output_path = "dist/lambda_src.zip"
}
```

If the `source_dir` contains the following:
```shell
-rw-r--r--  1 bdb  staff   14 15 Aug 14:12 file1.txt
-rw-r--r--  1 bdb  staff   14 15 Aug 14:12 file2.txt
-rw-r--r--  1 bdb  staff   14 15 Aug 14:12 file3.txt
```

Running `terraform apply` generates `lambda_src.zip` in the `dist` directory.

Running `unzip lambda_src.zip` in the `dist` directory then produces the following:
```shell
-rw-r--r--  1 bdb  staff   14  1 Jan  2049 file1.txt
-rw-r--r--  1 bdb  staff   14  1 Jan  2049 file2.txt
-rw-r--r--  1 bdb  staff   14  1 Jan  2049 file3.txt
-rw-r--r--  1 bdb  staff  412 16 Nov 15:56 lambda_src.zip
```

The archive (zip) did not contain a directory containing the files but just contains the files.
Can you confirm that you are seeing something different from this?
Thanks.

**Comment by sanspace** [comment] 2022-12-16 10:43
@bendbennett I left the org years back and I no longer have the same set up. If you do not see any issues, please go ahead and close this one. Thank you!

**Comment by bendbennett** [comment] 2022-12-16 12:08
@sanspace thanks for letting me know.

I'm going to close this as I cannot reproduce the [original issue](https://github.com/hashicorp/terraform-provider-archive/issues/56#issue-524614578).

**Closed by bendbennett** 2022-12-16 12:08 UTC
Labels: tf-devex-triage
